#!/bin/bash
function logMsg {
    message_level=$1
    message_itself=$2
    if [ $message_level -lt $LOG_LEVEL ]; then
        case $message_level in
            0) message_level_text="Error";;
            1) message_level_text="Warning";;
            2) message_level_text="Info";;
        esac
        echo "${message_level_text}: ${message_itself}"
    else
        echo "err level"
    fi
}

logMsg $*
